version: "3.8"

services:
    nginx:
        build: .
        ports:
            - "8080:8080"
        env_file: .nginx.env
        volumes:
            - "./nginx/conf:/nginx/conf"
        command: ["bash", "/nginx/start.sh"]
